language: node_js
os: linux
dist: focal
node_js:
  - 16
deploy:
  provider: pages
  strategy: git
  cleanup: false
  token: "$GITHUB_TOKEN"
  local_dir: dist
  keep_history: true
  on:
    branch: main
cache:
  directories:
    - node_modules
script:
  - npm run build
